# Generated by Django 3.2.5 on 2022-06-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nome do Dono')),
                ('nameAnimal', models.CharField(max_length=50, verbose_name='Nome do Animal')),
                ('date_init', models.DateField(verbose_name='Data De Entrada')),
                ('description', models.TextField(max_length=100, verbose_name='Descricao')),
                ('doc', models.FileField(upload_to='docs', verbose_name='Documentos')),
            ],
            options={
                'verbose_name': 'Internacao',
                'verbose_name_plural': 'Internacoes',
                'ordering': ['id'],
            },
        ),
    ]
