# Generated by Django 4.0.5 on 2022-06-15 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['id'], 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        # migrations.RemoveField(
        #     model_name='consulta',
        #     name='raca_name',
        # ),
    ]
