# Generated by Django 4.0.5 on 2022-06-15 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racas', '0001_initial'),
        ('consulta', '0002_alter_consulta_options_remove_consulta_raca_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racas.raca')),
            ],
            options={
                'verbose_name': 'Raça',
                'verbose_name_plural': 'Raças',
                'ordering': ['id'],
            },
        ),
    ]
