# Generated by Django 4.0.5 on 2022-06-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0010_consultaraca_consulta_consulta_raca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='raca_name',
            field=models.CharField(default='Cachorro', max_length=100, verbose_name='racaAnimal'),
        ),
    ]
