# Generated by Django 4.0.5 on 2022-06-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0011_consulta_raca_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='consulta_raca',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='raca_name',
        ),
        migrations.AddField(
            model_name='consulta',
            name='hour',
            field=models.CharField(choices=[('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00')], default='09:00', max_length=5, verbose_name='Horario'),
        ),
        migrations.DeleteModel(
            name='ConsultaRaca',
        ),
    ]
