# Generated by Django 4.0.5 on 2022-06-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0014_consulta_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='photo',
            field=models.ImageField(upload_to='photos', verbose_name='Foto'),
        ),
    ]
