# Generated by Django 4.0.5 on 2022-06-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0016_remove_consulta_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos', verbose_name='Foto'),
        ),
    ]
