# Generated by Django 3.2.5 on 2022-06-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0018_remove_consulta_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos', verbose_name='Foto'),
        ),
    ]
