# Generated by Django 3.2.5 on 2022-06-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0019_consulta_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='photo',
            field=models.ImageField(upload_to='photos', verbose_name='Foto'),
        ),
    ]
