# Generated by Django 3.2.5 on 2022-06-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default='user', max_length=200, verbose_name='Senha'),
        ),
    ]
