# Generated by Django 3.2.5 on 2022-06-20 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
    ]
