# Generated by Django 3.2.5 on 2022-06-22 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_client_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cpf',
            field=models.CharField(default='', max_length=200, verbose_name='cpf'),
        ),
    ]
